# fly.toml app configuration file for ai-quiz-generator-v3
#
# See https://fly.io/docs/reference/configuration/ for details.
#

app = 'ai-quiz-generator-v3'

primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
[build]
  dockerfile = "Dockerfile"
